### ISSUE TITLE
UDPTrackerClient reverses IP addresses

### ISSUE THREAD

**Issue by marton200472** [bizzehdee/bzTorrent#23]
**Describe the bug**
UDPTrackerClient reverses received IP addresses, while it shouldn't.
For example 192.168.1.56 becomes 56.1.168.192.

**To Reproduce**
1. Announce to a UPD tracker containing a known IP.
2. Check the response, the IP address is reversed.

**Expected behavior**
The IP address should not be reversed.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Runtime: .NET 6

**Additional context**
I discovered this bug while working on my UDP tracker, but I tested it with other trackers as well, and the problem persisted.

**Comment by bizzehdee** [comment]
@marton200472 can you reopen or re-make this PR? im revisiting this library again, and would like to pull your fix in

**Comment by marton200472** [comment]
It is so hard not to start playing around with this library again 😃 
I might do it once i have some time again.
